const LocationData = {
  "Chhattisgarh": {
    "Packers Movers": [
      "Ambikapur",
      "Bhilai",
      "Durg",
      "Bilaspur",
      "Chirmiri",
      "Korba City",
      "Raigarh",
      "Raipur"
    ]
  },
  "Rajasthan": {
    "Packers Movers": [
      "Ajmer",
      "Alwar",
      "Jaipur",
      "Bhilwara",
      "Bikaner",
      "Chittorgarh",
      "Jaisalmer",
      "Jawahar Nagar",
      "Jodhpur",
      "Kota",
      "Malviya Nagar",
      "Sikar",
      "Udaipur",
      "Vaishali Nagar",
      "Vidhyadhar Nagar",
      "Nemrana",
      "Neem ka thana",
      "Sajhapur",
      "Sharapura"
    ]
  },
  "Uttar Pradesh": {
    "Packers Movers": [
      "Agra",
      "Gorakhpur",
      "Jhansi",
      "Kanpur",
      "Lucknow",
      "Mathura",
      "Meerut",
      "Varanasi"
    ]
  },
  "Delhi": {
    "Packers Movers": [
      "Delhi NCR",
      "Ghaziabad",
      "Noida",
      "Greater Noida",
      "Noida Sector 62",
      "Noida Sector 74",
      "Noida Sector 75",
      "Noida Sector 76",
      "Noida Sector 77",
      "Noida Sector 93",
      "Noida Sector 118",
      "Noida Sector 119",
      "Noida Sector 120",
      "Noida Sector 121",
      "Noida Extension",
      "Indirapuram",
      "Vaishali",
      "Lajpat Nagar",
      "Saket",
      "Rohini",
      "Vasant Kunj",
      "Vasant Vihar",
      "Mayur Vihar",
      "Shahdara",
      "R K Puram",
      "Janakpuri",
      "Uttam Nagar",
      "Dwarka Sector 21",
      "Dwarka Sector 23 ",
      "Dwarka Sector 24 ",
      "Paschim Vihar",
      "South Extension",
      "Punjabi Bagh",
      "Tilak Nagar",
      "Chanakyapuri",
      "Delhi Cantt",
      "Pitampura",
      "Vikaspuri",
      "Greater Kailash",
      "Hauz Khas",
      "Defence Colony",
      "Model Town",
      "Ashram",
      "Begumpur",
      "Alaknanda",
      "Anand Vihar",
      "Ashok Nagar",
      "Ashok Vihar",
      "Connaught Place",
      "Chandni Chowk",
      "Chattarpur",
      "Civil Lines",
      "Daryaganj",
      "Dashrath Puri",
      "Udyog Vihar",
      "Dhaula Kuan",
      "Dilshad Garden",
      "Dr Mukherjee Nagar",
      "Palam Vihar",
      "Sushant Lok",
      "DLF Phase 3 ",
      "DLF Phase 4 ",
      "DLF Phase 5 ",
      "Gurgaon",
      "Gurugram",
      "Gurgaon Vatika Sector 83 ",
      "Gurgaon Vatika Sector 84 ",
      "Gurgaon Vatika Sector 85 ",
      "Gurgaon Sector 5 ", "Gurgaon Sector 9", "Gurgaon Sector 10", "Gurgaon Sector 12", "Gurgaon Sector 14 ", "Gurgaon Sector 88", "Gurgaon Sector 83", "Gurgaon Sector 84",
      "Hero Honda Chowk",
      "IMT Manesar",
      "Farukh Nagar",
      "Faridabad",
      "Faridabad Sector 21 ",
      "Faridabad Sector 21A ",
      "Faridabad Sector 23 ",
      "Faridabad Sector 10 ",
      "Faridabad Sector 50 ",
      "Faridabad Sector 70 ",
      "Faridabad Sector 76 ",
      "Faridabad Sector 80 ",
      "Faridabad Sector 88 ",
      "Ballabhgarh",
      "Vinay Nagar Faridabad",
      "Jawahar Colony Faridabad",
      "New Friends Colony",
      "Pitam Pura",
      "Karkardooma",
      "Kirti Nagar",
      "Mahipalpur",
      "Malviya Nagar",
      "Moti Nagar",
      "Palam",
      "Patel Nagar",
      "Patparganj",
      "Paharganj",
      "Sarojini Nagar",
      "Shalimar Bagh",
      "Sheikh Sarai",
      "Maharani Bagh"
    ]

  },
  "Madhya Pradesh": {
    "Packers Movers": [
      "Bhopal",
    ]
  },
  "Chandigarh": {
    "Packers Movers": [
      "Chandigarh",
      "Panchkula",
      "mohali"
    ]
  },
  "Karnataka": {
    "Packers Movers": [
      "Bangalore",
      "Bellary",
      "Bengaluru",
      "Chikkamagaluru",
      "Mandya",
      "Mysore",
      "Raichur",
      "Yeshwanthpur",
      "Hubli",
      "Hospet",
      "Kanakapura Road",
      "Madikeri",
      "Mahadevapura",
      "Jalahalli",
      "Doddanekundi",
      "Hebbal",
      "Malleswaram",
      "Domlur",
      "Kammanahalli",
      "Indiranagar",
      "BTM Layout",
      "Marathahalli",
      "Koramangala",
      "Hosur Road",
      "JP Nagar",
      "Electronic City",
      "Jayanagar",
      "Ramamurthy Nagar",
      "Old Airport Road",
      "Bannerghatta Road",
      "Banashankari 3rd Stage",
      "MG Road",
      "Richmond Town",
      "HSR Layout",
      "Mysore Road",
      "Sarjapur Road",
      "RT Nagar",
      "Shivaji Nagar",
      "KR Puram",
      "Whitefield",
      "Mangalore",
      "Hennur Cross",
      "Yelahanka",
      "Bellandur",
      "Banaswadi",
      "Banashankari",
      "Bommanahalli"
    ]
  },

  "Maharashtra": {
    "Packers Movers": [
      "Mumbai",
      "Navi Mumbai",
      "Pune",
      "Nagpur",
      "Thane",
      "Airoli",
      "Alibaug",
      "Ambernath",
      "Ambivli",
      "Andheri",
      "Andheri East",
      "Andheri West",
      "Asangaon",
      "Atgaon",
      "Badlapur",
      "Ballard Estate",
      "Bangur Nagar",
      "Belapur",
      "Bhayander",
      "Bhiwandi",
      "Bhayandar East",
      "Bhayandar West",
      "Boisar",
      "Borivali",
      "Borivali East",
      "Borivali West",
      "Bhandup",
      "Dongri",
      "Mahim",
      "Dombivli",
      "Mulund",
      "Malad",
      "Vashi",
      "Kurla",
      "CST",
      "Santacruz",
      "Koparkhairane",
      "Bandra",
      "Dadar",
      "Juhu",
      "Powai",
      "Worli",
      "Colaba",
      "Chembur",
      "Goregaon",
      "Versova",
      "Vile Parle",
      "Ghatkopar",
      "Kandivali",
      "Parel",
      "Matunga",
      "Lokhandwala",
      "Saki Naka",
      "Pimple Saudagar",
      "Wakad",
      "Hinjewadi",
      "Kalyani Nagar",
      "Baner",
      "Bavdhan",
      "Kothrud",
      "Aundh",
      "Viman Nagar",
      "Dange Chowk",
      "Vishal Nagar",
      "Wagholi",
      "Pashan",
      "Magarpatta City",
      "Hadapsar",
      "Fatima Nagar",
      "Gurav",
      "Kharadi",
      "Warje",
      "Ravet",
      "Shivaji Nagar",
      "Pimpri Chinchwad",
      "Nigdi",
      "Nanded"
    ]
  },
  "Gujarat": {
    "Packers Movers": [
      "Ahmedabad",
      "Rajkot",
      "Surat",
      "Vadodara",
      "Gandhi Nagar",
      "Vapi",
      "Gandhi Dham",

    ]
  },
  "Haryana": {
    "Packers Movers": [
      "Bhiwani ",
      "Ambala",
      "Hisar",
      "Palwal",
      "Sonipat"
    ]
  },
  "Andhra Pradesh": {
    "Packers Movers": [
      "Visakhapatnam",
      "Anantapur",
      "Vijayawada",
    ]
  },

  "West Bengal": {
    "Packers Movers": [
      "Kolkata",
      "Alipore",
      "Ballygunge",
      "Barrackpore",
      "Behala",
      "Bidhannagar",
      "Dum Dum",
      "Durgapur",
      "Haldia",
      "Howrah",
      "Madhyamgram",
      "New Town",
      "Rajarhat",
      "Salt Lake",
      "Tollygunge",
      "Lake Garden",
      "Garia",
      "Gariahat",
      "Jadavpur",
      "Babu Hati",
      "Airport",
      "Shrirampur",
      "Hindmotor",
      "Rishra",
      "Belur",
      "Kalighat",
      "Jodhpur Park",
      "Jatin Das Park",
      "Santoshpur",
      "Kasba",
      "Science City",
      "Kalyani",
      "Titagarh",
      "Serampore",
      "Kestopur",
      "Ruby"
    ]
  },
  "Tamil Nadu": {
    "Packers Movers": [
      "Anna Nagar",
      "Adyar",
      "Velachery",
      "Tambaram",
      "Mylapore",
      "Royapettah",
      "Sholinganallur",
      "Kanchipuram",
      "Kilpauk",
      "Porur",
      "Poonamallee",
      "Nungambakkam",
      "Ambattur",
      "Kolathur",
      "Choolaimedu",
      "Chromepet",
      "Ekkaduthangal",
      "Thiruvanmiyur",
      "Tiruvottiyur",
      "Nanganallur",
      "Avadi",
      "Arakkonam",
      "Chengalpattu",
      "Navalur",
      "Thoraipakkam",
      "T Nagar",
      "Alwarpet",
      "Adambakkam",
      "Besant Nagar",
      "Kodambakkam",
      "Kelambakkam",
      "Medavakkam",
      "Madipakkam",
      "Mogappair",
      "Guduvanchery",
      "Pallikaranai",
      "Perungudi",
      "Ramapuram",
      "KK Nagar",
      "Kottivakkam",
      "East Coast Road",
      "Siruseri",
      "Perumbakkam",
      "Vadapalani",
      "Nolambur",
      "Kumbakonam",
      "Aminjikarai",
      "Kadapakkam",
      "Mandeville",
      "Mugalivakkam",
      "Kavankarai",
      "Maduravoyal",
      "Sriperumbudur",
      "Alandur",
      "Guindy",
      "Kadirvedu",
      "Peerkankaranai",
      "OMR",
      "Triplicane",
      "Mahindra World City",
      "Perungalathur",
      "Kolapakkam",
      "Iyyappanthangal"
    ]
  },
  "Additional Coverage": {
    "Packers Movers": [

      "Ghaziabad",
      "Bhopal",
      "Jaipur",
      "Indore",
      "Agra",
      "Delhi",
      "Vadodara",
      "Howrah",
      "Pimpri-Chinchwad",
      "Kanpur",
      "Patna",
      "Navi Mumbai",
      "Ludhiana",
      "Visakhapatnam",
      "Varanasi",
      "Dhanbad",
      "Faridabad",
      "Lucknow",
      "Allahabad",
      "Rajkot",
      "Bengaluru",
      "Srinagar",
      "Surat",
      "Vasai-Virar",
      "Jabalpur",
      "Mumbai",
      "Amritsar",
      "Hyderabad",
      "Chennai",
      "Gwalior",
      "Coimbatore",
      "Nagpur",
      "Kolkata",
      "Kalyan-Dombivli",
      "Ahmedabad",
      "Nashik",
      "Pune",
      "Thane",
      "Aurangabad"
    ]
  }
}
  ;
export default LocationData;